### ISSUE TITLE
Erro ao importar template no Zabbix 4.4

### ISSUE THREAD

**Issue by leandrosoaress** [GeorgeHPD/Zabbix#2]
Olá,
Poderia me auxiliar para que eu consiga importar o template do DVR?
Segue erro: Não foi possível ler o XML: (41) Specification mandate value for attribute data-pjax-transient [Linha: 53 | Coluna: 38].

**Comment by leandrosoaress** [comment]
Olá,
Consegui contornar o problema, eu estava salvando como ao invés de fazer o download do arquivo pelo botão do Git.
Obrigado pela contribuição.

**Comment by GeorgeHPD** [comment]
Boa noite, posso sim tem telegram ou Skype ?

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by leandrosoaress** [comment]
Olá,
Consegui contornar o problema, eu estava salvando como ao invés de fazer o download do arquivo pelo botão do Git.
Obrigado pela contribuição.

**Comment by GeorgeHPD** [comment]
Show, qualquer coisa pode chamar lá no telegram ou Skype

Tg: George_hpd

Skype: George_bsl

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
